barko/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.index, name='index'),
    path('journal', views.journal, name='journal'),
    path('parametres', views.parametres, name='parametres'),    
    
    path('inscription', views.inscription, name='inscription'),
    path('login', views.my_login, name='login'),
    path('logout', views.my_logout, name='logout'),

    path('dog_profil', views.dog_profil, name='dog_profil'), 
    path('single_dog/<int:dog_id>/', views.single_dog_profile, name='single_dog'), 
    path('add_dog', views.add_dog, name='add_dog'),
    path('add_breed', views.add_breed, name='add_breed'),
    path('delete_dog/<int:dog_id>', views.delete_dog, name='delete_dog'),

]



    # -------------FUTUR---------------------------
    # path('ajouter', views.ajouter, name='ajouter'),
    # path('maps', views.maps, name='maps'),
    # path('budget', views.budget, name='budget'),
    # path('objectif', views.objectif, name='objectif'),
    

barkolog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('barko.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

barko/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.db.models.signals import post_save
from django.dispatch import receiver

        

    
class Breed(models.Model):
    name_breed = models.CharField(max_length=30)    
    
    def __str__(self):
        return self.name_breed    
    
class FoodType(models.Model):
    name_food_type = models.CharField(max_length=30, blank=True, null=True)    
    
    def __str__(self):
        return self.name_food_type

class FoodBrand(models.Model):
    name_brand = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.name_brand
    
class Photo(models.Model):
    description_photo = models.CharField(max_length=255, blank=True, null=True)
    path_photo = models.ImageField(upload_to='dogs', null=True)
    date_photo = models.DateTimeField('date de publication de photo',default=datetime.datetime.now)
    
    def __str__(self):
        return self.description_photo
        

class Dog(models.Model):
    FEMALE = 'Femelle'
    MALE = 'Mâle'
    SEXE_CHOICES = [(FEMALE,'femelle'),(MALE,'mâle')]
    name_dog = models.CharField(max_length=30)
    avatar_dog = models.ImageField(upload_to='dog/dog_avatar', default='/default/8.png', editable=True)
    age_month_dog = models.DateField("date de naissance", default=now, editable=True)
    sex_dog = models.CharField('sexe du chien', choices=SEXE_CHOICES, blank=True, null=True, max_length=20, default=MALE)
    weight_dog = models.FloatField('poids du chien',default=0, null=True, blank=True)
    id_chip_dog = models.BigIntegerField(blank=True, null=True)
    sterilized = models.BooleanField('stériliser ou pas', null=True)
    breed_dog = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='race du chien' ,blank=True, null=True)
    photo = models.ManyToManyField(Photo, blank=True)

    def __str__(self):
        return self.name_dog 


class Owner(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE)
    age_owner = models.DateField("date de naissance", default=now, editable=True)
    avatar = models.ImageField(upload_to = 'user', default='default/avatar.jpg', editable=True)
    dog = models.ManyToManyField(Dog)

    @receiver(post_save, sender=User)
    def create_owner_profile(sender, instance, created, **kwargs):
        if created:
            Owner.objects.create(owner=instance)

    @receiver(post_save, sender=User)
    def save_owner_profile(sender, instance, **kwargs):
        instance.owner.save()

    def __str__(self):
        return self.owner.first_name


class Feeding(models.Model):
    quantity = models.IntegerField('Quantité en grams',default=0)
    begin_time = models.DateTimeField("début d'un repas", default=now, editable=True)
    end_time = models.DateTimeField(" fin du repas ", default=now, editable=True)
    comments = models.CharField(max_length=255, blank=True, null=True)
    type = models.ForeignKey(FoodType, on_delete=models.CASCADE, blank=True, null=True)
    brand = models.ForeignKey(FoodBrand, on_delete=models.CASCADE, blank=True)
    photo = models.ManyToManyField(Photo, blank=True)   
    dog = models.ManyToManyField(Dog)

    def __str__(self):
        return self.type.name_food_type
        
class Walk(models.Model):
    name = models.CharField(max_length=30, default='quotidienne', editable=True)
    begin_time= models.DateTimeField('date/heure de debut', default=now, editable=True)
    end_time = models.DateTimeField('date/heure de fin', default=now, editable=True)
    comments = models.CharField(max_length=200, blank=True, null=True)
    photo_walk = models.ImageField(upload_to='walks', blank= True)
    dog = models.ManyToManyField(Dog)
    
    
    def __str__(self):
        return self.name

class Vaccine(models.Model):
    name_vacinne = models.CharField(max_length=30)
    date_vaccine = models.DateField('', blank=True, null=True)
    vaccinated = models.BooleanField('yes or no', blank=True, null=True)
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE, blank=True, null=True)   
    
    def __str__(self):
        return self.name_vacinne
    
    

barko/forms.py
from django.forms import ModelForm 
from .models import Breed, Dog, Feeding, Owner, Photo
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class UserRegisterForm(UserCreationForm):  
    class Meta:
        model = User
        fields = ( 'first_name', 'last_name', 'email', 'password1', 'password2')
        first_name = forms.CharField(required=True)
        widgets = {
            'first_name':forms.TextInput(attrs={'class': 'form-control', 'required':True}),
            'last_name':forms.TextInput(attrs={'class': 'form-control', 'required':True}),
            'email':forms.EmailInput(attrs={'class': 'form-control', 'required':True}),
            'password1':forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2':forms.PasswordInput(attrs={'class': 'form-control'}),
        } 
        labels = {
            'first_name':'Prénom',
            'last_name':'Nom',
            'email':'Adress mail',
            'password1':'Mot de passe',
            'password2':'Confirmer mot de passe ',
        } 
    
    def __init__(self,*args,**kwargs):        
        """ passe 'class':'form-control' au champs password1 et password2 
        -> BOOTSTRAP RENDERING
        """
        super(UserRegisterForm,self).__init__(*args,**kwargs)
        self.fields['password1'].widget.attrs['class']= 'form-control'
        self.fields['password2'].widget.attrs['class']= 'form-control'
        self.fields['password1'].label = 'Mot de passe'
        self.fields['password2'].label = 'Confirmer mot de passe'







class DogCreateForm(ModelForm):

    class Meta :
        model = Dog
        fields = ('name_dog', 'avatar_dog',  'age_month_dog','sex_dog', 'weight_dog','id_chip_dog','sterilized','breed_dog')
        breed_dog =forms.ChoiceField()
        
        
        labels ={
            'name_dog':'Nom du chien',
            'avatar_dog':'Photo du chien',
            'age_month_dog':'Date de naissance',
            'sex_dog':'le sexe du chien',
            'weight_dog':'Poids',
            'id_chip_dog':'Puce d\'intification',
            'sterilized':'Steriliser',
            'breed_dog':'',      
        }
        widgets ={
            'name_dog':forms.TextInput(attrs={'class': 'form-control mt-2 mb-4'}),
            'avatar_dog':forms.ClearableFileInput(attrs={'class': 'form-control mt-2 mb-4'}),
            'age_month_dog':forms.DateInput(attrs={'class': 'form-control mt-2 mb-4', 'type':'date'}),
            'sex_dog':forms.Select(attrs={'class': 'form-select mt-2 mb-4'}),
            'weight_dog':forms.NumberInput(attrs={'min':'0', 'type': 'number','class':'form-control mt-2 mb-4'}),
            'id_chip_dog':forms.NumberInput(attrs={'min':'100000000000000', 'max':'999999999999999', 'placeholder':'code unique de 15 chiffres ',
                                                    'class':'form-control mt-2 mb-4'}),
            'sterilized':forms.CheckboxInput(attrs={'class':'form-check-input mt-2 mb-4 col-12'}),
            'breed_dog':forms.Select(attrs={'class': 'form-select mt-2 mb-4', 'placeholder':'race du chien'}),  
        }

class BreedCreateForm(ModelForm):

    class Meta:
        model = Breed
        fields = ('name_breed',)
        name_breed = forms.CharField()
        labels ={
            'name_breed':'Nom de la race'
        }
        widgets = {
            'name_breed':forms.TextInput(attrs={'class': 'form-control'}),
        }




# class OwnerRegisterForm(ModelForm):    
#     class Meta:
#         model = Owner
#         fields =('name', 'age_owner', 'avatar')       
#         widgets ={
#             'age_owner':forms.DateInput(attrs={'class':'form-control'}),
#             'avatar':forms.ClearableFileInput(attrs={'class': 'form-control'}),
#             'name':forms.TextInput(attrs={'class': 'form-control'})
#         } 

barko/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import IntegrityError
from .forms import UserRegisterForm,  BreedCreateForm,DogCreateForm

from .models import Breed, Dog,Owner, Walk

# ------------------Authentification----------------------------

# LOGIN
def my_login(request):
    if request.method == 'POST':
        email = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'connexion reussi')
            user = Owner.objects.get(pk=request.user.id)
            dog = Dog.objects.filter(owner=user)
            if dog :
                return redirect('index')
            else:
                messages.success(request, ('veuillez ajouter un chien pour proceder plus loin'))
                return redirect ('add_dog')
        else:
            messages.success(request, ("L'utilisateur ou le mot de passe n'existe pas "))
            return redirect('login')
    else:
        return render(request, 'barko/login.html')    

#  REGISTER
def inscription(request):
    user_form = UserRegisterForm()
    if request.method == 'POST':
        user_form = UserRegisterForm(request.POST or None)
        if user_form.is_valid():
            try:
                last_name = request.POST['last_name']
                firstname = request.POST['first_name']
                pwd = request.POST['password1']
                email = request.POST['email']
                username = email
                user = User.objects.create_user(username, email, pwd)    
                user.last_name = last_name
                user.first_name = firstname
                user.save()                
                login(request,user)
                messages.success(request, ('inscripton reussi'))
                messages.success(request, ('veuillez ajouter un chien pour proceder plus loin'))
                return redirect ('add_dog')                
            except IntegrityError : 
                messages.error(request, ('Un compte éxiste déja '))
                user_form = UserRegisterForm()
                context = {'user_form': user_form } 
                return render(request, 'barko/inscription.html',context) 
        else:
            messages.error(request, ('Veuillez corriger le formulaire.'))
    else:
        user_form = UserRegisterForm()
    context = {'user_form': user_form } 
    return render(request, 'barko/inscription.html',context) 

# LOGOUT
def my_logout(request):
    logout(request)
    messages.success(request, ('déconnexion reussi'))
    return redirect('index')



# --------------------------APP----------------------------

# HOME
@login_required(login_url='login')   
def index(request):
    user = request.user.owner
    dog = Dog.objects.filter(owner=user)
    walk = Walk.objects.all
    context={'dog_list':dog, 'user':user, 'walk':walk}
    return render(request, 'barko/index.html', context)

# DOG ACTIVITIES VIEW
@login_required(login_url='login')   
def journal(request):
    user = request.user.owner
    dog = Dog.objects.filter(owner=user)
    return render(request, 'barko/journal.html', {'dog_list': dog, 'user':user})

# ---------------------------DOG CRUD-----------------------

# CREATE DOG
@login_required(login_url='login')  
def add_dog(request):
    dog_form = DogCreateForm()  
    owner = Owner.objects.get(owner=request.user)     
    if request.method == 'POST': 
        dog_form = DogCreateForm(request.POST or None,  request.FILES or None)
        if dog_form.is_valid():
            new_dog = dog_form.save()
            owner.dog.add(new_dog)
            owner.save()
            messages.success(request, ('Chien enrengistré'))
            return redirect('index')
        else:
            dog_form = DogCreateForm()
            messages.error(request, ('verifier les informations'))
    else:
        dog_form = DogCreateForm()
    return render(request,'dog/add_dog.html', {'dog_form': dog_form})


#  READ DOG LIST
@login_required(login_url='login')   
def dog_profil(request):
    user = request.user.owner
    dog = Dog.objects.filter(owner=user )
    return render(request, 'dog/dog_profil.html', {'dogs': dog, 'user':user})


# UPDATE SINGLE DOG 
@login_required(login_url='login')   
def single_dog_profile(request, dog_id): 
    dog = Dog.objects.get(id=dog_id)  
    form = DogCreateForm(request.POST or None, request.FILES or None, instance=dog)
    if form.is_valid():
        form.save()
        messages.success(request, 'informations mise a jour')
        return redirect('dog_profil')
    context={'dog': dog, 'form':form}
    return  render(request, 'dog/single_dog.html', context) 

# DELETE SINGLE DOG
@login_required(login_url='login')   
def delete_dog(request, dog_id):
    dog = Dog.objects.get(id=dog_id)
    dog.delete()
    messages.success(request, ('Le chien a été supprimer'))
    return redirect('dog_profil')


# *-----------------------------USER ------------------------

# READ USER
@login_required(login_url='login')   
def right(request):
    current_user = request.user
    user= User.objects.get(user=current_user)
    return render(request, 'base/right.html', {'user':user})


# ----------------------------ADMIN-------------------------
@login_required(login_url='login')  
def add_breed(request):
    breed_form = BreedCreateForm()
    if request.method == 'POST':    
        breed_form = BreedCreateForm(request.POST or None)
        if breed_form.is_valid():
            breed_form.save()
            messages.success(request, ('la race a bien été ajouter'))
            return redirect('add_dog')
    else:
        breed_form = BreedCreateForm()
    return render(request, 'dog/add_breed.html', {'breeds': breed_form})



























# ---------------------------------FUTUR--------------------------

@login_required(login_url='login')   
def parametres(request):    
    context={}
    return render(request, 'barko/parametres.html', context)

# def ajouter(request):
#     return render(request, 'barko/ajouter.html')

# def maps(request):
#     return render(request, 'barko/maps.html')

# def budget(request):
#     return render(request, 'barko/budget.html')

# def objectif(request):
#     return render(request, 'barko/objectif.html')

barko/templates/dog/add_breed.html
{% extends 'base/base.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}


{% block contenue %}

<!-- <div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Subscribe our Newsletter</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
				<p>Subscribe to our mailing list to get the latest updates straight in your inbox.</p>
                <form>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email Address">
                    </div>
                    <button type="submit" class="btn btn-primary">Subscribe</button>
                </form>
            </div>
        </div>
    </div>
</div> -->
<h1>Ajouter une race</h1>
<form method="POST" action="">
{% csrf_token %}
{{breeds}}
<button type="submit" class="btn btn-primary mt-4">Submit</button>    
<!-- <div class="modal fade" id="myModal" tabindex="-1"  data-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLabel">Ajouter une race de chien</h1>
        </div>
        <div class="modal-body">
            <div class="mb-3">
                <label class="required form-label" for="id_name_breed">Name de la race:</label>
                <input type="text" name="name_breed" value="" class="form-control" maxlength="50" required="" id="id_name_breed">
            </div>        
        </div>
        <div class="modal-footer">
        <a href="{% url 'add_dog' %}"><button type="button"  class="btn btn-secondary" data-bs-dismiss="modal">Retour</button></a>
        <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Save changes</button>
        </div>
    </div>
    </div>
</div> -->
</form>
{% endblock %}

barko/templates/dog/add_dog.html
{% extends 'base/base.html' %}
{% load static %}



{% block contenue %}

    <h1>Ajouter un nouveau chien </h1>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ dog_form }}       
    <br> 
    <button type="submit" class="btn btn-primary mt-4">Submit</button>    
    </form>

{% endblock %}

barko/templates/dog/dog_profil.html
{% extends 'base/base.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
<div class="container">
    <h1>Profile des chiens</h1>
    <div class="row">
        {% for dog in dogs %}
            <a class="col-auto col-xl-1" href="{% url 'single_dog' dog.id %}">
                <div class="profile">
                    <div class=" profile-photo">
                        <img src="{{ dog.avatar_dog.url }}" >
                    </div>
                    <div class="info text-center">
                        <p><b>{{ dog.name_dog }}</b></p>
                    </div>
                </div>
            </a>
        {% endfor%}               
            <div class="col-auto">
                <a href="{% url 'add_dog' %}"><button class="btn btn-primary">Ajouter un chien</button></a>
            </div>
    </div>
</div>

    
{% endblock %}

barko/templates/dog/single_dog.html
{% extends 'barko/index.html' %}
{% load active_link_tags %}
{% load static %}
{% load i18n %}

{% block contenue %}
<div class="container ">
  <form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    
      {{form}}
      <div class="row">
        
        <div class="col-auto ">
          <button type="submit" class="btn btn-warning ">Modifier</button> 
        </div>

        <div class="col-auto">
          <span class="btn btn-danger " data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Supprimer
          </span>
        </div>
        <div class="col-auto ">
          <a href="{% url 'dog_profil' %}"><span class ="btn btn-warning" class="btn btn-warning ">Retour</span></a>
        </div>
      </div> 
  </form>

          
          <div class="collapse" id="collapseExample">
            <div class="card card-body ">
              <h4>Confirmation de la suppresion </h4>
              <div class="row">
                <a href="{% url 'delete_dog' dog.id %}" class="col-auto" ><span class="btn btn-info mt-2">oui</span></a>
                <a href="" class="col-auto" ><span class="btn btn-info mt-2">non</span></a>
              </div>
            </div>
          </div>
        </div>
        
      </div>



{% endblock %}